package: community.lazycat.app.headscale
version: 0.29.3
name: Headscale
description: Self-hosted Tailscale control server with Headplane Web UI
author: headscale
license: BSD-3-Clause
homepage: https://github.com/juanfont/headscale
min_os_version: 1.5.0
locales:
  zh:
    name: Headscale
    description: 带 Headplane Web 管理界面的自托管 Tailscale 控制服务器
    entries.headplane.title: Headplane
    entries.headscale.title: Headscale
  en:
    name: Headscale
    description: Self-hosted Tailscale control server with Headplane Web UI
    entries.headplane.title: Headplane
    entries.headscale.title: Headscale
permissions:
  required:
    - net.internet
